---
- name: "Setup cli"
  template:
    src: scripts/bin/haya-cli
    dest: /usr/bin/haya-cli
    mode: 0755

- name: "Create general directory structure"
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ bc_path_general }}"
    - "{{ bc_path_general }}/{{ bc_name }}"

- name: "Set components to bench"
  set_fact:
    bc_component_name: "bench"

- name: "Setup {{ bc_name }}-{{ bc_component_name }} container"
  when:
    - bc_haya_comp_state_bench == "present"
  include_tasks: "../../bench/main.yml"

- name: "Set components to wallet"
  set_fact:
    bc_component_name: "wallet"

- name: "Setup {{ bc_name }}-{{ bc_component_name }} container"
  when:
    - bc_haya_comp_state_wallet == "present"
  include_tasks: "blockchain/{{ bc_name }}/{{ bc_component_name }}.yml"

- name: "Set components to boot"
  tags:
    - always
  set_fact:
    bc_component_name: "boot"

- name: "Setup {{ bc_name }}-{{ bc_component_name }} container"
  tags:
    - always
  when:
    - bc_haya_comp_state_boot == "present"
  include_tasks: "blockchain/{{ bc_name }}/{{ bc_component_name }}.yml"

- name: "Setup metrics to {{ bc_component_name }}"
  when:
    - install_promstack
    - bc_haya_comp_state_boot == "present"
  include_tasks: "metrics/{{ bc_component_name }}.yml"

- name: "Set components to prod"
  tags:
    - always
  set_fact:
    bc_component_name: "prod"

- name: "Setup {{ bc_name }}-{{ bc_component_name }} container"
  tags:
    - always
  when:
    - bc_haya_comp_state_prod == "present"
  include_tasks: "blockchain/{{ bc_name }}/{{ bc_component_name }}.yml"

- name: "Setup metrics to {{ bc_component_name }}"
  when:
    - install_promstack
    - bc_haya_comp_state_prod == "present"
  include_tasks: "metrics/{{ bc_component_name }}.yml"

- name: "Set components to metrics"
  tags:
    - monitoring
  set_fact:
    bc_component_name: "monitoring"

- name: "Setup metrics to {{ bc_component_name }}"
  when:
    - install_promstack
    - bc_haya_comp_state_monitoring == "present"
  include_tasks: "metrics/{{ item }}.yml"
  with_items:
    - "{{ bc_component_name }}"
    - "targets"
